# Web Scraping

In [142]:
import pandas as pd 
import requests
from bs4 import BeautifulSoup

In [143]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get("https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1", headers = headers).text

In [144]:
soup = BeautifulSoup(webpage, "lxml")

In [145]:
company = soup.find_all("div", class_= "companyCardWrapper__primaryInformation")

In [146]:
name = [ ]
rating = [ ]
reviews = [ ]
Type_location = [ ]
rated_for =[ ]
#Critical_rated_for = [ ]

for i in company:
    name.append(i.find("a", class_= "companyCardWrapper__companyName").text.strip())
    rating.append(i.find("div", class_= "rating_text rating_text--md").text.strip())
    reviews.append(i.find("span", class_ = "companyCardWrapper__companyRatingCount").text.strip())
    Type_location.append(i.find("span", class_= "companyCardWrapper__interLinking").text.strip())
    rated_for.append(i.find("span", class_ = "companyCardWrapper__ratingValues").text.strip())
    #Critical_rated_for.append(i.find("span", class_ = "companyCardWrapper__ratingValues").text.strip())

In [147]:
d = {"name": name, "rating": rating, "reviews": reviews, "Type_Location": Type_location, "Top_rated_for": rateded_for}

In [148]:
df = pd.DataFrame(d)

In [168]:
df

,name,rating,reviews,Type_Location,Top_rated_for
0,Alldigi Tech,3.9,(2.5k),BPO | Chennai +36 other locations,"Work Life Balance, Job Security"
1,JCB,3.8,(2.5k),Industrial Machinery | Pune +111 other locations,Work Life Balance
2,Sterlite Technologies,3.8,(2.5k),Hardware & Networking | Chhatrapati Sambhajina...,"Promotions, Job Security"
3,Northern Trust Operating Services,3.6,(2.5k),Financial Services | Bengaluru +27 other locat...,"Promotions, Salary, Work Satisfaction"
4,Bajaj Electricals,3.9,(2.5k),Consumer Electronics & Appliances | Mumbai +23...,"Work Life Balance, Salary"
5,Tractors and Farm Equipment,3.9,(2.5k),Industrial Machinery | Chennai +192 other loca...,"Work Life Balance, Skill Development"
6,Sammaan Capital Limited,3.7,(2.5k),NBFC | Gurugram +199 other locations,Work Life Balance
7,Parle Agro,3.9,(2.5k),Beverage | Mumbai +259 other locations,"Work Life Balance, Job Security"
8,Adani Group,3.8,(2.5k),Power | Ahmedabad +201 other locations,Promotions
9,CorroHealth Infotech,3.6,(2.5k),Analytics & KPO | Hyderabad +38 other locations,Salary
10,ICICI Securities,3.9,(2.5k),Financial Services | Mumbai +151 other locations,"Job Security, Work Life Balance, Company Culture"
11,Planet Spark,3.8,(2.5k),EdTech | Gurugram +59 other locations,"Skill Development, Company Culture"
12,Emcure Pharmaceuticals,3.6,(2.5k),Pharma | Pune +119 other locations,"Promotions, Job Security, Company Culture"
13,Biocon Limited,4.0,(2.5k),Biotechnology | Bengaluru +66 other locations,"Work Life Balance, Company Culture, Job Security"
14,McDonald's,3.9,(2.4k),Hospitality | New Delhi +151 other locations,"Skill Development, Job Security"
15,Intellect Design Arena,3.5,(2.4k),Software Product | Chennai +40 other locations,Job Security
16,Hero FinCorp,3.9,(2.4k),NBFC | New Delhi +395 other locations,"Work Life Balance, Company Culture"
17,TaskUs,3.0,(2.4k),BPO | Indore +37 other locations,"Promotions, Job Security, Skill Development"
18,Paras Hospital,4.1,(2.4k),Healthcare | Patna +60 other locations,"Work Life Balance, Skill Development, Salary"
19,Datamatics Global Services,3.4,(2.4k),IT Services & Consulting | Mumbai +37 other lo...,"Promotions, Salary, Company Culture"

In [172]:
final = pd.DataFrame()

for j in range(1, 100):
    url = "https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={}".format(j)

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(url, headers = headers).text
    
    soup = BeautifulSoup(webpage, "lxml")
    company = soup.find_all("div", class_= "companyCardWrapper__primaryInformation")
    
    name = [ ]
    rating = [ ]
    reviews = [ ]
    Type_location = [ ]
    rated_for = [ ]

    for i in company:
        name.append(i.find("a", class_= "companyCardWrapper__companyName").text.strip())
        rating.append(i.find("div", class_= "rating_text rating_text--md").text.strip())
        reviews.append(i.find("span", class_ = "companyCardWrapper__companyRatingCount").text.strip())
        Type_location.append(i.find("span", class_= "companyCardWrapper__interLinking").text.strip())
        rated_for.append(i.find("span", class_ = "companyCardWrapper__ratingValues").text.strip())
    
    d = {"name": name, "rating": rating, "reviews": reviews, "Type_Location": Type_location, "Top_rated_for": rated_for}
    df = pd.DataFrame(d)
    
    final = pd.concat([final, df], ignore_index = True)

In [170]:
final

,name,rating,reviews,Type_Location,Top_rated_for
0,TCS,3.3,(1.1L),IT Services & Consulting | Bengaluru +444 othe...,Job Security
1,Accenture,3.7,(73.7k),IT Services & Consulting | Bengaluru +259 othe...,"Promotions, Salary, Work Satisfaction"
2,Wipro,3.6,(65.3k),IT Services & Consulting | Hyderabad +373 othe...,"Promotions, Salary, Work Satisfaction"
3,Cognizant,3.7,(61.7k),IT Services & Consulting | Hyderabad +232 othe...,"Promotions, Salary, Work Satisfaction"
4,Capgemini,3.6,(53.6k),IT Services & Consulting | Bengaluru +182 othe...,"Work Life Balance, Job Security"
...,...,...,...,...,...
375,Intellect Design Arena,3.5,(2.4k),Software Product | Chennai +40 other locations,Job Security
376,Hero FinCorp,3.9,(2.4k),NBFC | New Delhi +395 other locations,"Work Life Balance, Company Culture"
377,TaskUs,3.0,(2.4k),BPO | Indore +37 other locations,"Promotions, Job Security, Skill Development"
378,Paras Hospital,4.1,(2.4k),Healthcare | Patna +60 other locations,"Work Life Balance, Skill Development, Salary"
379,Datamatics Global Services,3.4,(2.4k),IT Services & Consulting | Mumbai +37 other lo...,"Promotions, Salary, Company Culture"

In [173]:
final.to_csv("Companies.csv", index = False)